# Generated by Django 5.0.14 on 2025-04-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='panorama_metadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=400)),
                ('gps_lat', models.FloatField()),
                ('gps_lng', models.FloatField()),
                ('orientation', models.IntegerField()),
                ('camera_make', models.CharField(max_length=100)),
                ('camera_model', models.CharField(max_length=100)),
                ('software', models.CharField(max_length=100)),
                ('date_taken', models.DateTimeField()),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'panorama_metadata',
            },
        ),
    ]
