# Generated by Django 5.0.14 on 2025-04-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panorama_metadata',
            name='gps_direction',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
