# Generated by Django 5.0.14 on 2025-04-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_panorama_metadata_gps_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='panorama_metadata',
            name='gps_alt',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
