# Generated by Django 5.0.14 on 2025-04-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_panorama_metadata_gps_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='panorama_metadata',
            name='name',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='panorama_metadata',
            constraint=models.UniqueConstraint(fields=('name', 'gps_lat', 'gps_lng', 'gps_alt'), name='unique_panorama_fields'),
        ),
    ]
