# Generated by Django 5.0.14 on 2025-04-18 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='panorama_metadata',
            new_name='PanoramaMetadata',
        ),
    ]
