# Generated by Django 5.0.14 on 2025-04-18 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0002_rename_panorama_metadata_panoramametadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panoramametadata',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stratiview.state'),
        ),
    ]
