# Generated by Django 5.0.14 on 2025-04-18 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0003_alter_panoramametadata_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telefono',
            new_name='phone',
        ),
    ]
