# Generated by Django 4.2.11 on 2025-04-29 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0003_alter_user_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stratiview.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_route',
            },
        ),
        migrations.AddConstraint(
            model_name='userroute',
            constraint=models.UniqueConstraint(fields=('user', 'route'), name='unique_user_route_fields'),
        ),
    ]
