# Generated by Django 5.0.14 on 2025-04-18 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0004_rename_telefono_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panoramametadata',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stratiview.state'),
            preserve_default=False,
        ),
    ]
