# Generated by Django 4.2.11 on 2025-04-30 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0004_userroute_userroute_unique_user_route_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panoramametadata',
            name='url',
        ),
    ]
