# Generated by Django 5.0.14 on 2025-04-23 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0004_rename_telefono_user_phone'),
    ]

    operations = [
        # First, remove the unique constraint
        migrations.RemoveConstraint(
            model_name='panoramametadata',
            name='unique_panorama_fields',
        ),
        # Then, alter the field
        migrations.AlterField(
            model_name='panoramametadata',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stratiview.state'),
            preserve_default=False,
        ),
        # Finally, re-add the unique constraint
        migrations.AddConstraint(
            model_name='panoramametadata',
            constraint=models.UniqueConstraint(
                fields=['name', 'gps_lat', 'gps_lng', 'gps_alt', 'state'], 
                name='unique_panorama_fields'
            ),
        ),
    ]

