# Generated by Django 4.2.11 on 2025-05-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0005_remove_panoramametadata_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
    ]
