# Generated by Django 5.0.14 on 2025-04-18 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0005_alter_panoramametadata_state'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='panoramametadata',
            name='unique_panorama_fields',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='telefono',
        ),
    ]
