# Generated by Django 4.2.11 on 2025-05-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0006_remove_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
