# Generated by Django 5.0.14 on 2025-04-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0006_remove_panoramametadata_unique_panorama_fields_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='panoramametadata',
            constraint=models.UniqueConstraint(fields=('name', 'gps_lat', 'gps_lng', 'gps_alt', 'state'), name='unique_panorama_fields'),
        ),
    ]
