# Generated by Django 4.2.11 on 2025-05-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0007_route_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='state',
        ),
    ]
