# Generated by Django 5.0.14 on 2025-04-18 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0007_panoramametadata_unique_panorama_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telefono',
            new_name='phone',
        ),
    ]
