# Generated by Django 5.0.14 on 2025-04-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0008_rename_telefono_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
