# Generated by Django 4.2.11 on 2025-05-07 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0008_remove_route_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
    ]
