# Generated by Django 5.0.14 on 2025-04-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0009_user_failed_attempts_user_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='panoramametadata',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
