# Generated by Django 4.2.11 on 2025-05-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0009_delete_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanormaMakers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yaw', models.FloatField()),
                ('pitch', models.FloatField()),
                ('key', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('panorama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stratiview.panoramametadata')),
            ],
            options={
                'db_table': 'panorama_markers',
            },
        ),
    ]
