# Generated by Django 5.0.14 on 2025-04-23 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0010_panoramametadata_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stratiview.state'),
        ),
    ]
