# Generated by Django 4.2.11 on 2025-05-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0010_panormamakers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PanormaMakers',
            new_name='PanoramaMakers',
        ),
    ]
