# Generated by Django 4.2.11 on 2025-05-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0011_rename_panormamakers_panoramamakers'),
    ]

    operations = [
        migrations.AddField(
            model_name='panoramamakers',
            name='type',
            field=models.CharField(choices=[('terrestre', 'Terrestre'), ('aereo', 'Aéreo'), ('interior', 'Interior')], default='terrestre', max_length=100),
        ),
    ]
