# Generated by Django 5.0.14 on 2025-04-23 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0011_alter_user_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stratiview.area')),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='UserArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stratiview.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_area',
            },
        ),
        migrations.CreateModel(
            name='UserRol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stratiview.rol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_rol',
            },
        ),
        migrations.AddConstraint(
            model_name='rol',
            constraint=models.UniqueConstraint(fields=('name', 'area'), name='unique_rol_fields'),
        ),
        migrations.AddConstraint(
            model_name='userarea',
            constraint=models.UniqueConstraint(fields=('user', 'area'), name='unique_user_area_fields'),
        ),
        migrations.AddConstraint(
            model_name='userrol',
            constraint=models.UniqueConstraint(fields=('user', 'rol'), name='unique_user_rol_fields'),
        ),
    ]
