# Generated by Django 5.2 on 2025-04-25 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0012_area_rol_userarea_userrol_rol_unique_rol_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panoramametadata',
            name='upload_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
