# Generated by Django 4.2.11 on 2025-05-15 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0012_panoramamakers_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panoramamakers',
            name='type',
            field=models.CharField(choices=[('land', 'Terrestre'), ('air', 'Aéreo'), ('inside', 'Interior')], default='land', max_length=100),
        ),
    ]
