# Generated by Django 4.2.11 on 2025-05-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0013_alter_panoramamakers_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panoramamakers',
            name='type',
            field=models.CharField(choices=[('vehicle', 'En vehículo'), ('air', 'Aéreo'), ('inside', 'Interior'), ('walk', 'A pie')], default='vehicle', max_length=100),
        ),
    ]
