# Generated by Django 4.2.11 on 2025-05-16 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0014_alter_panoramamakers_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PanoramaMakers',
            new_name='PanoramaPropertyMakers',
        ),
        migrations.AlterModelTable(
            name='panoramapropertymakers',
            table='panorama_property_markers',
        ),
    ]
