# Generated by Django 4.2.11 on 2025-05-16 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0015_rename_panoramamakers_panoramapropertymakers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panoramapropertymakers',
            name='type',
        ),
        migrations.CreateModel(
            name='PanoramaTourMarkers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yaw', models.FloatField()),
                ('pitch', models.FloatField()),
                ('type', models.CharField(choices=[('vehicle', 'En vehículo'), ('air', 'Aéreo'), ('inside', 'Interior'), ('walk', 'A pie')], default='vehicle', max_length=100)),
                ('panorama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stratiview.panoramametadata')),
            ],
            options={
                'db_table': 'panorama_tour_markers',
            },
        ),
        migrations.AddConstraint(
            model_name='panoramatourmarkers',
            constraint=models.UniqueConstraint(fields=('yaw', 'pitch', 'panorama'), name='unique_panorama_tour_markers_fields'),
        ),
    ]
