# Generated by Django 4.2.11 on 2025-05-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0016_remove_panoramapropertymakers_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panoramametadata',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='panoramametadata',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('route',), name='unique_default_panorama_per_route'),
        ),
    ]
