# Generated by Django 4.2.11 on 2025-05-16 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0017_panoramametadata_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panoramatourmarkers',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stratiview.route'),
        ),
        migrations.AlterField(
            model_name='panoramametadata',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stratiview.route'),
        ),
        migrations.AlterField(
            model_name='userroute',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stratiview.route'),
        ),
    ]
