# Generated by Django 4.2.11 on 2025-05-19 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0021_consolidated_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanoramaObjectMarkers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('yaw', models.FloatField()),
                ('pitch', models.FloatField()),
                ('description', models.CharField(max_length=200)),
                ('panorama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stratiview.panoramametadata')),
            ],
            options={
                'db_table': 'panorama_object_markers',
            },
        ),
        migrations.AddConstraint(
            model_name='panoramaobjectmarkers',
            constraint=models.UniqueConstraint(fields=('yaw', 'pitch', 'panorama'), name='unique_panorama_object_markers_fields'),
        ),
    ]
