# Generated by Django 4.2.11 on 2025-05-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0022_panoramaobjectmarkers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='type',
            field=models.CharField(choices=[('vehicle', 'En vehículo'), ('air', 'Aéreo'), ('inside', 'Interior'), ('walk', 'A pie')], default='vehicle', max_length=100),
        ),
    ]
