# Generated by Django 4.2.11 on 2025-05-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0023_route_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panoramapropertymakers',
            old_name='account',
            new_name='property_type',
        ),
        migrations.RemoveField(
            model_name='panoramapropertymakers',
            name='key',
        ),
        migrations.AddField(
            model_name='panoramapropertymakers',
            name='business_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='panoramapropertymakers',
            name='land_position',
            field=models.CharField(blank=True, choices=[('esquinero', 'esquinero'), ('intermedio', 'Intermerdio'), ('Manzanero', 'Manzanero'), ('frentes no contiguos', 'Frentes no contiguis'), ('paso de servicio', 'Paso de servicioo')], default='intermedio', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='panoramapropertymakers',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panoramapropertymakers',
            name='size',
            field=models.CharField(blank=True, choices=[('pequeño', 'pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], default='mediano', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='panoramapropertymakers',
            name='updated_use',
            field=models.CharField(choices=[('comercial', 'Comercial'), ('industrial', 'Industrial'), ('equipamiento', 'Equipamiento'), ('mixto', 'Mixto'), ('residencial', 'Residencial')], default='residencial', max_length=50),
        ),
        migrations.AlterField(
            model_name='panoramatourmarkers',
            name='type',
            field=models.CharField(choices=[('vehiculo', 'Vehiculo'), ('aereo', 'Aereo'), ('interior', 'Interior'), ('a pie', 'A pie')], default='vehiculo', max_length=100),
        ),
    ]
