# Generated by Django 4.2.11 on 2025-05-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stratiview', '0024_rename_account_panoramapropertymakers_property_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Implementta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
                ('gps_lat', models.FloatField()),
                ('gps_lng', models.FloatField()),
            ],
            options={
                'db_table': 'implementta',
            },
        ),
        migrations.AlterField(
            model_name='panoramapropertymakers',
            name='land_position',
            field=models.CharField(blank=True, choices=[('Esquinero', 'esquinero'), ('Intermedio', 'Intermerdio'), ('Manzanero', 'Manzanero'), ('Frentes no contiguos', 'Frentes no contiguis'), ('Paso de servicio', 'Paso de servicioo')], default='intermedio', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='panoramapropertymakers',
            name='size',
            field=models.CharField(blank=True, choices=[('Pequeño', 'pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], default='mediano', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='panoramapropertymakers',
            name='updated_use',
            field=models.CharField(choices=[('Comercial', 'Comercial'), ('Industrial', 'Industrial'), ('Equipamiento', 'Equipamiento'), ('Mixto', 'Mixto'), ('Residencial', 'Residencial')], default='residencial', max_length=50),
        ),
    ]
